baseURL = 'https://aboutme-gtap.onrender.com/'
languageCode = 'vi'
title = 'BNGroup'
theme = "stack"

copyright = "¬© 2025 BNGroup - All Rights Reserved"

[params]
  [params.sidebar]
    emoji = "üëã"
    title = "BNGroup"
    subtitle = "Code ‚Ä¢ Guitar ‚Ä¢ Game ‚Ä¢ Business"
    [params.sidebar.avatar]
      enabled = true
      local = false
      src = "/portrait/BuiBinhNguyen.png"

  [params.footer]
    since = 2025
    customText = "¬© BNGroup - All Rights Reserved"

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.article]
    math = false
    toc = true
    readingTime = true
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.widgets]
    [[params.widgets.homepage]]
      type = "search"
    [[params.widgets.homepage]]
      type = "archives"
      [params.widgets.homepage.params]
        limit = 5
    [[params.widgets.homepage]]
      type = "categories"
      [params.widgets.homepage.params]
        limit = 10
    [[params.widgets.homepage]]
      type = "tag-cloud"
      [params.widgets.homepage.params]
        limit = 10
    [[params.widgets.page]]
      type = "toc"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/SuKem0703/"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/binh.nguyen.250862"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@Sheeppp"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Ch·ªß"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "courses"
    name = "Kh√≥a H·ªçc (LTM)"
    url = "/courses/"
    weight = 20
    
  [[menu.main]]
    identifier = "projects"
    name = "D·ª± √Ån (Projects)"
    url = "/projects/chronicles-of-knight-and-mage/"
    weight = 15

  [[menu.main]]
    identifier = "blog"
    name = "Blog C√° Nh√¢n"
    url = "/posts/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "V·ªÅ T√¥i (Profile)"
    url = "/about/"
    weight = 40

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
