baseURL = 'https://aboutme-gtap.onrender.com/'
languageCode = 'vi'
title = 'BNGroup'
theme = "PaperMod"

copyright = "© 2025 BNGroup - All Rights Reserved"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  label.text = "BNGroup"

  [params.profileMode]
    enabled = true
    title = "Chào mừng đến với BNGroup" 
    subtitle = "Code • Guitar • Game • Business"
    imageUrl = "portrait/BuiBinhNguyen.png"
    imageTitle = "CEO BNGroup"
    imageWidth = 120
    imageHeight = 120

    [[params.profileMode.buttons]]
      name = "Dự án cá nhân"
      url = "https://github.com/SuKem0703/"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/SuKem0703/"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/binh.nguyen.250862"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@Sheeppp"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "courses"
    name = "Khóa Học (LTM)"
    url = "/courses/"
    weight = 20
    
  [[menu.main]]
    identifier = "projects"
    name = "Dự Án (Projects)"
    url = "/projects/chronicles-of-knight-and-mage/"
    weight = 15

  [[menu.main]]
    identifier = "blog"
    name = "Blog Cá Nhân"
    url = "/posts/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "Về Tôi (Profile)"
    url = "/about/"
    weight = 40

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
