baseURL = 'https://aboutme-gtap.onrender.com/'
languageCode = 'vi'
title = 'BNGroup'
theme = "stack"

copyright = "BNGroup - All Rights Reserved"

[params]
  mainSections = ["posts", "projects", "courses"]
  [params.sidebar]
    #emoji = "üëë"
    title = "B√πi B√¨nh Nguy√™n"
    subtitle = "Code ‚Ä¢ Guitar ‚Ä¢ Game ‚Ä¢ Business"
    [params.sidebar.avatar]
      enabled = true
      local = false
      src = "/portrait/BuiBinhNguyen.png"

  [params.footer]
    since = 2025
    customText = "BNGroup - All Rights Reserved"

  [params.dateFormat]
    published = "02/01/2006"
    lastUpdated = "02/01/2006 15:04 MST"

  [params.article]
    math = false
    toc = true
    readingTime = true
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  [params.widgets]
    [[params.widgets.homepage]]
      type = "search"
    [[params.widgets.homepage]]
      type = "archives"
      [params.widgets.homepage.params]
        limit = 5
    [[params.widgets.homepage]]
      type = "categories"
      [params.widgets.homepage.params]
        limit = 10
    [[params.widgets.homepage]]
      type = "tag-cloud"
      [params.widgets.homepage.params]
        limit = 100
    [[params.widgets.page]]
      type = "toc"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Ch·ªß"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "courses"
    name = "Kh√≥a H·ªçc (LTM)"
    url = "/courses/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "D·ª± √Ån"
    url = "/projects/chronicles-of-knight-and-mage/"
    weight = 15

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "V·ªÅ T√¥i"
    url = "/about/"
    weight = 40

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/SuKem0703/"
    params.icon = "brand-github"

  [[menu.social]]
    name = "Facebook"
    url = "https://www.facebook.com/binh.nguyen.250862"
    params.icon = "link"

  [[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/@Sheeppp"
    params.icon = "link"
    weight = 20

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true